apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp9-deployment
  namespace: webappspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp9
  template:
    metadata:
      labels:
        app: webapp9
    spec:
      containers:
      - name: webapp9
        image: guylan85/webapp9
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: webapp9-service
  namespace: webappspace
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: webapp9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapi-frontend-deployment
  namespace: webappspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapi-frontend
  template:
    metadata:
      labels:
        app: reactapi-frontend
    spec:
      containers:
      - name: reactapi-frontend
        image: guylan85/reactapi-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactapi-frontend-service
  namespace: webappspace
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: reactapi-frontend
