apiVersion: v1
kind: Namespace
metadata:
  name: webappspace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webappspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: guylan85/webapp1234
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
